### ISSUE TITLE
When executing "pip install -r requirements.txt; a problem occurs"

### ISSUE THREAD

**Issue by luohongk** [openxrlab/xrdslam#1]
When executing "pip install -r requirements.txt"; the following situation occurs and it gets stuck: "Building wheels for collected packages: pytorch3d, diff_gaussian_rasterization, tinycudann, evaluate_3d_reconstruction, mathutils, torch_scatter, fvcore, iopath
  Building wheel for pytorch3d (setup.py)"
![2024-05-14_16-18](https://github.com/openxrlab/xrdslam/assets/134777945/097d49f8-6033-470f-9e96-28342f9dcbf6)

**Comment by wangxiaomeng030** [comment]
It seems like the installation process is currently building wheels for the listed packages. If it remains stuck for an extended period, you can try installing each package individually from the requirements.txt file. For example, you could install pytorch3d by running pip install git+https://github.com/facebookresearch/pytorch3d.git, and install open3d version 0.16.0 by running pip install open3d==0.16.0.
