### ISSUE TITLE
RGBD dataloader need devices.yaml

### ISSUE THREAD

**Issue by antonyvan** [openxrlab/xrdslam#14]
Hi,
Thank you guys very much for this fantastic work.
I am testing your code by following your introduction.
I get this error   when I run ds-run co-slam --data  data/replica/Replica/office0  --data-type replica
FileNotFoundError: [Errno 2] No such file or directory: 'data/replica/Replica/office0/devices.yaml'

It seems the data doesn't have devices.yaml
how could I fix the issue?
Thanks.

**Comment by wangxiaomeng030** [comment]
You should place the device.yaml file from this path （https://github.com/openxrlab/xrdslam/blob/main/configs/replica/devices.yaml） in the testing directory.

**Comment by antonyvan** [comment]
Thanks
