### ISSUE TITLE
The program is stuck with no error reported

### ISSUE THREAD

**Issue by DY-ATL** [openxrlab/xrdslam#9]
The terminal looks like this
```
[19:20:20] Saving config to: outputs/config.yml
  0%|                                                      | 0/2000 [00:00<?, ?it/s]
```

**Comment by wangxiaomeng030** [comment]
Which algorithm is being run here? Some algorithms iterate 1000 times on the first frame, so they may run slowly. You can try Co-SLAM first to quickly verify the environment setup; alternatively, you can directly modify the iteration count for the corresponding algorithm in input_config.py to avoid it getting stuck.

**Comment by DY-ATL** [comment]
I used point-slam and stucks. I try co-slam and it works! Thank you!

Is the speed normal for a RTX3090 GPU?
64%|███████████████▎                   | 1285/2000 [22:00<12:58,  1.09s/it]

I'm new to SLAM area. Can you recommend some paper on dense visual SLAM? (We have monocular/stereo camera, IMU, **without depth map**. Deep learning based methods are preferred. Need to run real-time on robot.) Thanks again!

**Comment by wangxiaomeng030** [comment]
Co-SLAM runs very quickly, while Point-SLAM and SplaTAM run relatively slower. You can refer to the runtime details in [our paper](https://arxiv.org/abs/2410.23690). Additionally, the algorithms currently integrated in XRDSLAM only support RGBD-SLAM. If you don’t have depth images, you may consider using an RGB-SLAM approach, such as [Splat-SLAM](https://github.com/google-research/Splat-SLAM).

**Comment by DY-ATL** [comment]
Thank you!
